import sys
from PyQt5 import QtWidgets as qtw
from PyQt5 import QtCore as qtc
from PyQt5 import QtSql as qts

from gradecrossingform.models.model_crossing_assessment_ca import ModelCrossingAssessmentCA
from gradecrossingform.views.view_crossing_assessment_ca import ViewCrossingAssessmentCA
#from GradeCrossingForm.db.db_crossing_assessment_ca import DBCrossingAssessmentCA

class ControllerCrossingAssessmentCA(qtw.QWidget):
    def __init__(self):
        super().__init__() # create default constructor for QWidget
        #self.db = DBCrossingAssessmentCA()
        self.view = ViewCrossingAssessmentCA()
        self.model = ModelCrossingAssessmentCA(self.view)

        self.connect_and_emit_trigger()
        #self.map_fields_to_sql()

    def connect_and_emit_trigger(self):
        self.view.changed.connect(self.model.collision_history_total_5_year_period)        
        self.view.changed.connect(self.model.collision_history_risk_index_initial)
        self.view.changed.connect(self.model.collision_history_risk_index_final)
        self.view.changed.connect(self.model.general_info_rail_no_tracks_total)
        self.view.changed.connect(self.model.general_info_rail_no_trains_per_day_total)
        self.view.changed.connect(self.model.general_info_road_no_traffic_lanes_total)
        self.view.changed.connect(self.model.general_info_rail_railway_design_speed)
        self.view.changed.connect(self.model.design_calculate_adjacent_track_clearance_time)
        self.view.changed.connect(self.model.design_calculate_clearance_time_pedestrian_design_check)
        self.view.changed.connect(self.model.design_calculate_clearance_time_vehicle_design_check)
        
        #TODO 
        #self.view.label_design_measure_clearance_distance_gate_arm_ssd = qtw.QLabel('no Value')
        
        self.view.changed.connect(self.model.design_calculate_clearance_time_gate_arm_vehicle_ssd)
        self.view.changed.connect(self.model.design_calculate_clearance_time_gate_arm_vehicle_stop)
        self.view.changed.connect(self.model.design_calculate_clearance_time_gate_arm_vehicle_recommended)
        self.view.changed.connect(self.model.design_calculate_vehicle_departure_time)
        self.view.changed.connect(self.model.design_calculate_vehicle_departure_time_grade_adjusted)
        self.view.changed.connect(self.model.design_calculate_vehicle_departure_time_gate_arm_clearance)
        
        #TODO
        #connect signals and slots - design_calculate_vehicle_departure_time_gate_arm_clearance_grade_adjusted
        self.view.changed.connect(self.model.design_calculate_vehicle_departure_time_gate_arm_clearance_grade_adjusted)
        self.view.changed.connect(self.model.design_lookup_design_vehicle_class)
        self.view.changed.connect(self.model.design_lookup_design_vehicle_length)
        self.view.changed.connect(self.model.design_lookup_grade_adjustment_factor)

        #TODO
        #connect signals and slots - design_measure_clearance_distance_gate_arm_stop

        self.view.changed.connect(self.model.road_geometry_lookup_gradient_difference)
        self.view.changed.connect(self.model.sightlines_lookup_existing_active_crossing)        
        self.view.changed.connect(self.model.sightlines_lookup_existing_active_crossing_with_gates)
        self.view.changed.connect(self.model.sightlines_calculate_dstopped_pedestrian_min_ft)        
        self.view.changed.connect(self.model.sightlines_calculate_dstopped_pedestrian_min_m)
        self.view.changed.connect(self.model.sightlines_calculate_dstopped_vehicle_min_ft)
        self.view.changed.connect(self.model.sightlines_calculate_dstopped_vehicle_min_m)
        self.view.changed.connect(self.model.sightlines_lookup_ssd_minimum_n_or_e_approach)
        self.view.changed.connect(self.model.sightlines_lookup_ssd_minimum_s_or_w_approach)
        self.view.changed.connect(self.model.sightlines_calculate_dssd_vehicle_min_ft)
        self.view.changed.connect(self.model.sightlines_calculate_dssd_vehicle_min_m)
        self.view.changed.connect(self.model.gcws_warrant_private_9_3_1)
        self.view.changed.connect(self.model.gcws_warrant_private_9_3_2_a)
        self.view.changed.connect(self.model.gcws_warrant_private_9_3_2_b)
        self.view.changed.connect(self.model.gcws_warrant_private_9_3_2_c)
        
        #TODO
        #connect signals and slots - gcws_warrant_public_9_1
        # .valueChanged.connect(self.gcws_warrant_public_9_1)

        self.view.changed.connect(self.model.gcws_warrant_public_9_1_a)
        self.view.changed.connect(self.model.gcws_warrant_public_9_1_b)
        self.view.changed.connect(self.model.gcws_warrant_public_9_1_c)
        self.view.changed.connect(self.model.gcws_warrant_public_9_1_d_i)
        self.view.changed.connect(self.model.gcws_warrant_public_9_1_d_ii)
        self.view.changed.connect(self.model.gcws_warrant_public_9_1_d_iii)
        
        #connect signals and slots - gcws_warrant_sidewalk_9_5
        #TODO add design vehcile pedestrian
        self.view.changed.connect(self.model.gcws_warrant_sidewalk_9_5)
        self.view.changed.connect(self.model.gates_gcws_warrant_private_9_4_1_a)
        self.view.changed.connect(self.model.gates_gcws_warrant_private_9_4_1_b)
        self.view.changed.connect(self.model.gates_gcws_warrant_private_9_4_1_c)
        self.view.changed.connect(self.model.gates_gcws_warrant_public_9_2_1_a)
        self.view.changed.connect(self.model.gates_gcws_warrant_public_9_2_1_b)
        self.view.changed.connect(self.model.gates_gcws_warrant_public_9_2_1_c)
        self.view.changed.connect(self.model.gates_gcws_warrant_public_9_2_1_d)
        self.view.changed.connect(self.model.gates_gcws_warrant_public_9_2_1_e)
        self.view.changed.connect(self.model.gates_gcws_warrant_sidewalk_9_6)

        #grade CROSSING warnING systEMS (GCS seCTION 12-16)
        #TODO
        #connect signals and slots - gcws_rail_design_warning_time_adjacent_crossing
        # .valueChanged.connect(self.gcws_rail_design_warning_time_adjacent_crossing)
        
        #TODO includes pedestrian clearance
        self.view.changed.connect(self.model.gcws_rail_design_warning_time_clearance_distance)        
        self.view.changed.connect(self.model.gcws_rail_design_warning_time_departure_time_vehicle)
        self.view.changed.connect(self.model.gcws_rail_design_warning_time_departure_time_pedestrian)
        self.view.changed.connect(self.model.gcws_rail_design_warning_time_gate_arm_clearance)
 
        #TODO Remove pedestrian clearance distance
        # self.view.doubleSpinBox_design_measure_clearance_distance_pedestrian.valueChanged.connect(self.model.gcws_rail_design_warning_time_gate_arm_clearance('doubleSpinBox_design_measure_clearance_distance_pedestrian', val))
        self.view.changed.connect(self.model.gcws_rail_design_warning_time_gate_arm_clearance)
        
        #TODO
        #connect signals and slots - gcws_rail_design_warning_time_preemption
        # .valueChanged.connect(self.gcws_rail_design_warning_time_preemption)
        
        self.view.changed.connect(self.model.gcws_rail_design_warning_time_ssd)

        #TODO
        # connect signals and slots - gcws_rail_design_approach_warning_time
        # .valueChanged.connect(self.gcws_rail_design_approach_warning_time)
        
        self.view.changed.connect(self.model.gates_gcws_calculate_inner_gate_arm_delay_time_recommended)
        self.view.changed.connect(self.model.aawd_calculate_advance_activation_time_design_n_or_e_approach)
        self.view.changed.connect(self.model.aawd_calculate_advance_activation_time_design_s_or_w_approach)
        self.view.changed.connect(self.model.aawd_calculate_distance_sign_and_stop_n_or_e_approach_recommended)
        self.view.changed.connect(self.model.aawd_calculate_distance_sign_and_stop_s_or_w_approach_recommended)
        self.view.changed.connect(self.model.aawd_warrant_gcr_lookup_road_classification)
        self.view.changed.connect(self.model.aawd_warrant_mutcd_lookup_road_speed_limit_greater_than_90_km_per_hr)
        self.view.changed.connect(self.model.preemption_of_traffic_signals_lookup_proximity_condition)
        self.view.changed.connect(self.model.preemption_of_traffic_signals_lookup_required)
        self.view.changed.connect(self.model.areas_without_train_whistling_lookup_gcs_9_2)
        self.view.changed.connect(self.model.areas_without_train_whistling_lookup_table_d1_criteria)
        self.view.changed.connect(self.model.areas_without_train_whistling_requirements_observe_table_D1)

    def map_fields_to_sql(self):
    # Map the crossing fields
        self.mapper = qtw.QdataWidgetMapper(self)
        self.mapper.setModel(self.db.db_model_crossing_assessment_ca)
        self.mapper.setItemDelegate(
            qts.QSqlRelationalDelegate(self))
        #self.mapper.addMapping(
        #    self.view.temp,
        #    self.db.db_model_crossing_assessment_ca.fieldIndex('functional_location')
        #)
        self.mapper.addMapping(
            self.view.label_aawd_calculate_advance_activation_time_design_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_calculate_advance_activation_time_design_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.label_aawd_calculate_advance_activation_time_design_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_calculate_advance_activation_time_design_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.label_aawd_calculate_distance_sign_and_stop_n_or_e_approach_recommended,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_calculate_distance_sign_and_stop_n_or_e_approach_recommended')
        )
        self.mapper.addMapping(
            self.view.label_aawd_calculate_distance_sign_and_stop_s_or_w_approach_recommended,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_calculate_distance_sign_and_stop_s_or_w_approach_recommended')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_aawd_measure_distance_sign_and_stop_n_or_e_approach_actual,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_measure_distance_sign_and_stop_n_or_e_approach_actual')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_aawd_measure_distance_sign_and_stop_s_or_w_approach_actual,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_measure_distance_sign_and_stop_s_or_w_approach_actual')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_observe_present_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_observe_present_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_observe_present_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_observe_present_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.spinBox_aawd_rail_advance_activation_time_actual_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_rail_advance_activation_time_actual_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.spinBox_aawd_rail_advance_activation_time_actual_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_rail_advance_activation_time_actual_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_road_aawd_sufficient_activation_time_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_road_sufficient_activation_time_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_road_aawd_sufficient_activation_time_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_road_sufficient_activation_time_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.label_aawd_warrant_gcr_lookup_road_classification,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_warrant_gcr_lookup_road_classification')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_warrant_gcr_observe_environmental_condition,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_warrant_gcr_observe_environmental_condition')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_warrant_gcr_observe_sightline_obstruction,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_warrant_gcr_observe_sightline_obstruction')
        )
        self.mapper.addMapping(
            self.view.label_aawd_warrant_mutcd_lookup_road_speed_limit_greater_than_90_km_per_hr,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_warrant_mutcd_lookup_road_speed_limit_greater_than_90')
        )
        self.mapper.addMapping(
            self.view.comboBox_aawd_warrant_mutcd_lookup_significant_road_downgrade,
            self.db.db_model_crossing_assessment_ca.fieldIndex('aawd_warrant_mutcd_lookup_significant_road_downgrade')
        )
        self.mapper.addMapping(
            self.view.comboBox_areas_without_train_whistling_observe_trespassing_area,
            self.db.db_model_crossing_assessment_ca.fieldIndex('areas_without_train_whistling_observe_trespassing_area')
        )
        self.mapper.addMapping(
            self.view.comboBox_areas_without_train_whistling_rail_anti_whistling_zone,
            self.db.db_model_crossing_assessment_ca.fieldIndex('areas_without_train_whistling_rail_anti_whistling_zone')
        )
        self.mapper.addMapping(
            self.view.comboBox_areas_without_train_whistling_rail_anti_whistling_zone_24_hrs,
            self.db.db_model_crossing_assessment_ca.fieldIndex('areas_without_train_whistling_rail_anti_whistling_zone_24_hrs')
        )

        self.mapper.addMapping(
            self.view.comboBox_areas_without_train_whistling_lookup_gcs_12_to_16,
            self.db.db_model_crossing_assessment_ca.fieldIndex('areas_without_train_whistling_lookup_GCS_12_to_16')
        )
        self.mapper.addMapping(
            self.view.label_areas_without_train_whistling_lookup_gcs_9_2,
            self.db.db_model_crossing_assessment_ca.fieldIndex('areas_without_train_whistling_lookup_gcs_9_2')
        )
        self.mapper.addMapping(
            self.view.label_areas_without_train_whistling_lookup_table_d1_criteria,
            self.db.db_model_crossing_assessment_ca.fieldIndex('label_areas_without_train_whistling_lookup_table_d1_criteria')
        )
        self.mapper.addMapping(
            self.view.label_areas_without_train_whistling_observe_table_D1,
            self.db.db_model_crossing_assessment_ca.fieldIndex('label_areas_without_train_whistling_observe_table_D1')
        )
        self.mapper.addMapping(
            self.view.comboBox_areas_without_train_whistling_observe_for_stop_and_proceed,
            self.db.db_model_crossing_assessment_ca.fieldIndex('areas_without_train_whistling_observe_for_stop_and_proceed')
        )
        self.mapper.addMapping(
            self.view.textEdit_collision_history_comments,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_comments')
        )
        self.mapper.addMapping(
            self.view.spinBox_collision_history_fatal_injury,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_fatal_injury')
        )
        self.mapper.addMapping(
            self.view.spinBox_collision_history_fatalities,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_fatalities')
        )
        self.mapper.addMapping(
            self.view.spinBox_collision_history_personal_injuries,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_personal_injuries')
        )
        self.mapper.addMapping(
            self.view.spinBox_collision_history_personal_injury,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_personal_injury')
        )
        self.mapper.addMapping(
            self.view.spinBox_collision_history_property_damage,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_property_damage')
        )
        self.mapper.addMapping(
            self.view.label_collision_history_total_5_year_period,
            self.db.db_model_crossing_assessment_ca.fieldIndex('collision_history_total_5_year_period')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_adjacent_track_clearance_time,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_adjacent_track_clearance_time')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_clearance_time_pedestrian_design_check,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_clearance_time_pedestrian_design_check')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_clearance_time_vehicle_design_check,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_clearance_time_vehicle_design_check')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_clearance_time_gate_arm_vehicle_ssd,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_clearance_time_gate_arm_vehicle_ssd')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_clearance_time_gate_arm_vehicle_stop,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_clearance_time_gate_arm_vehicle_stop')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_vehicle_travel_distance,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_vehicle_travel_distance')
        )
        self.mapper.addMapping(
            self.view.label_design_input_reaction_time,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_input_reaction_time')
        )
        self.mapper.addMapping(
            self.view.label_design_lookup_design_vehicle_class,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_lookup_design_vehicle_class')
        )
        self.mapper.addMapping(
            self.view.label_design_lookup_design_vehicle_length,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_lookup_design_vehicle_length')
        )
        self.mapper.addMapping(
            self.view.label_design_lookup_grade_adjustment_factor,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_lookup_grade_adjustment_factor')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_vehicle_departure_time,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_vehicle_departure_time')
        )
        self.mapper.addMapping(
            self.view.label_design_calculate_vehicle_departure_time_gate_arm_clearance,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_calculate_vehicle_departure_time_gate_arm_clearance')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_design_measure_adjacent_track_clearance_distance,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_measure_adjacent_track_clearance_distance')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_design_measure_adjacent_track_separation_distance,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_measure_adjacent_track_separation_distance')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_design_measure_clearance_distance_pedestrian,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_measure_clearance_distance_pedestrian')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_design_measure_clearance_distance_vehicle,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_measure_clearance_distance_vehicle')
        )
        self.mapper.addMapping(
            self.view.label_design_measure_clearance_distance_gate_arm_ssd,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_measure_clearance_distance_gate_arm_ssd')
        )
        self.mapper.addMapping(
            self.view.label_design_measure_clearance_distance_gate_arm_stop,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_measure_clearance_distance_gate_arm_stop')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_observe_field_acceleration_times_exceed_td,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_field_acceleration_times_exceed_td')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_observe_k_factor_crossing_nearby_intersection,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_k_factor_crossing_nearby_intersection')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_observe_k_factor_crossing_surface_condition,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_k_factor_crossing_surface_condition')
        )
        self.mapper.addMapping(
            self.view.textEdit_design_observe_k_factor_other,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_k_factor_other')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_observe_k_factor_pavement_marking_condition,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_k_factor_pavement_marking_condition')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_observe_k_factor_superelevation,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_k_factor_superelevation')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_observe_k_factor_vehicle_restrictions,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_observe_k_factor_vehicle_restrictions')
        )
        self.mapper.addMapping(
            self.view.comboBox_design_road_design_vehicle_type,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_road_design_vehicle_type')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_design_road_max_approach_grade_within_s,
            self.db.db_model_crossing_assessment_ca.fieldIndex('design_road_max_approach_grade_within_s')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_light_units_measure_mast_height_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_measure_mast_height_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_light_units_measure_mast_height_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_measure_mast_height_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_light_units_measure_cantilever_dl_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_measure_cantilever_dl_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_light_units_measure_cantilever_dl_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_measure_cantilever_dl_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_light_units_measure_cantilever_dr_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_measure_cantilever_dr_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.doubleSpinBox_light_units_measure_cantilever_dr_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_measure_cantilever_dr_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_supplemental_intersection_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_supplemental_intersection_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_supplemental_intersection_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_supplemental_intersection_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_supplemental_sidewalk_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_supplemental_sidewalk_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_supplemental_sidewalk_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_supplemental_sidewalk_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_visibility_back_lights_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_visibility_back_lights_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_visibility_back_lights_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_visibility_back_lights_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_visibility_front_lights_n_or_e_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_visibility_front_lights_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.comboBox_light_units_observe_visibility_front_lights_s_or_w_approach,
            self.db.db_model_crossing_assessment_ca.fieldIndex('light_units_observe_visibility_front_lights_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_private_9_3,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_private_9_3')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_private_9_3_1,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_private_9_3_1')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_private_9_3_2_a,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_private_9_3_2_a')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_private_9_3_2_b,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_private_9_3_2_b')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_private_9_3_2_c,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_private_9_3_2_c')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1_a,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1_a')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1_b,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1_b')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1_c,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1_c')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1_d_i,
             self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1_d_i')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1_d_ii,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1_d_ii')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_public_9_1_d_iii,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_public_9_1_d_iii')
        )
        self.mapper.addMapping(
            self.view.label_gcws_warrant_sidewalk_9_5,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_warrant_sidewalk_9_5')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_private_9_4_1_a,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_private_9_4_1_a')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_private_9_4_1_b,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_private_9_4_1_b')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_private_9_4_1_c,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_private_9_4_1_c')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_public_9_2_1_a,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_public_9_2_1_a')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_public_9_2_1_b,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_public_9_2_1_b')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_public_9_2_1_c,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_public_9_2_1_c')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_public_9_2_1_d,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_public_9_2_1_d')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_public_9_2_1_e,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_public_9_2_1_e')
        )
        self.mapper.addMapping(
            self.view.label_gates_gcws_warrant_sidewalk_9_6,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_warrant_sidewalk_9_6')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_lookup_clearance_time_gate_arm_design')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_observe_gate_arm_rest')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_observe_gate_ascent_time')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_observe_gate_descent_time')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_rail_gate_arm_delay_time_actual')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_rail_gate_arm_descent_time')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gates_gcws_rail_inner_gate_arm_delay_time_actual')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_bell_If_sidewalk')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_bells')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_bells_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_bells_number')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_cantilever_lights')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_cantilever_lights_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_cantilever_lights_number')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_gates')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_gates_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_gates_number')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_gcws_limited_Use_With_walk_light_assembly')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_gcws_limited_Use_without_walk_light_assembly')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_light_units')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_light_units_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_light_units_number')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_warning_signal_assemblies')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_warning_system_Housing_location')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_warning_time_consistency')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_observe_warning_time_consistency_Reduced_speed')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_crossing_warning_time_actual')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_cut_out_circuit_requirements')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_design_approach_warning_time')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_directional_stick_circuit_requirements')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_equipment_reaction_time')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_event_data_recorder')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_foreign_railway_interconnect')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_method_of_train_detection')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_remote_monitoring_and_access')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_self_diagnostic')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('gcws_rail_video_recorder')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_max_railway_operating_speed_freight')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_max_railway_operating_speed_passenger')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_railway_design_speed')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_no_tracks_main')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_no_tracks_other')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_no_tracks_total')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_no_trains_per_day_freights')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_no_trains_per_day_passenger')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_rail_no_trains_per_day_total')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_aadt_current')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_aadt_forecasted')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_aadt_year_current')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_aadt_year_forecasted')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_assistive_pedestrian_devices')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_bicycle_lane_n_or_e_side')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_bicycle_lane_s_or_w_side')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_classification')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_cyclist_per_day')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_no_traffic_lanes_bidirectional')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_no_traffic_lanes_northbound_or_easttbound')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_no_traffic_lanes_southbound_or_westbound')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_no_traffic_lanes_total')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_pedestrians_per_day')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_sidewalk_n_or_e_side')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_sidewalk_s_or_w_side')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_speed_design')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_speed_posted')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_sub_classification')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_road_traffic_median')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('general_info_train_switching')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_crossing_surface_extension_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_crossing_surface_extension_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_crossing_surface_length')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_distance_between_signal_mast_and_sidewalk_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_distance_between_signal_mast_and_sidewalk_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_elevation_top_of_rail_above_road_surface')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_elevation_top_of_rail_below_road_surface')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_flangeway_depth')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_flangeway_width')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_road_surface_Median_width')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_road_surface_shoulder_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_road_surface_shoulder_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_road_surface_travel_lanes_width_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_road_surface_travel_lanes_width_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_side_grinding_depth')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_side_grinding_width')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_sidewalk_extension_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_sidewalk_extension_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_sidewalk_width_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_measure_sidewalk_width_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_observe_road_approach_surface_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_observe_road_approach_surface_type')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_observe_crossing_smoothness')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_observe_crossing_surface_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('crossing_surface_observe_Material')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_assessment_Team')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_Country')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_crossing_location')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_crossing_status')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_Date_assessment')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_functional_location')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_gcws_type')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_grade_crossing_type')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_latitude')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_longitude')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_location_reference')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_mile')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_municipality')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_private_crossing_use')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_province')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_railway_authority')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_railway_operators')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_reason_for_assessment')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_road_authority')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_road_name')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_road_number')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_seniority')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_spur_mile')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_spur_name')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_subdivision_mile')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_subdivision_name')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_tc_crossing_number')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_track_ID')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('inspection_details_track_type')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('location_of_grade_crossing_nearest_intersection_other_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('location_of_grade_crossing_nearest_intersection_other_s_of_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('location_of_grade_crossing_nearest_intersection_signalized_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('location_of_grade_crossing_nearest_intersection_signalized_s_of_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('location_of_grade_crossing_nearest_intersection_stop_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('location_of_grade_crossing_nearest_intersection_stop_s_of_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_encroachment_near_crossing_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_encroachment_near_crossing_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_queuing_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_simultaneous_interconnection_advance_of_crossing')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_supplemental_signage')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_traffic_clearance_time_adequate')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_observe_unintended_queuing_by_traffic_signals')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_rail_preemption_warning_time_actual')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_road_or_rail_Crossing_preemption_type')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_road_preemption_warning_time_design')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('preemption_of_traffic_signals_warrant_proximity_condition')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_lookup_gradient_difference')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_measure_railway_cross_slope')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_measure_slope_between_8m_and_18m_nearest_rail_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_measure_slope_between_8m_and_18m_nearest_rail_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_measure_slope_Within_5m_nearest_rail_at_sidewalk')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_measure_slope_Within_8m_nearest_rail_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_measure_slope_Within_8m_nearest_rail_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_observe_alignment_horizontal_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_observe_alignment_horizontal_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_observe_lane_width_crossing_vs_approach_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_observe_lane_width_crossing_vs_approach_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_observe_smooth_alignment_within_ssd_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_observe_smooth_alignment_within_ssd_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_rail_superelevation')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_rail_superelevation_rate')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_road_crossing_angle')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_road_general_approach_grade_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('road_geometry_road_general_approach_grade_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_calculate_dssd_vehicle_min_ft')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_calculate_dssd_vehicle_min_m')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_calculate_dstopped_pedestrian_min_ft')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_calculate_dstopped_pedestrian_min_m')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_calculate_dstopped_vehicle_min_ft')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_calculate_dstopped_vehicle_min_m')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_lookup_stopping_sight_distance_minimum_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_lookup_stopping_sight_distance_minimum_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_Dssd_actual_n_or_e_approach_driver_left')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_Dssd_actual_n_or_e_approach_driver_right')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_Dssd_actual_s_or_w_approach_driver_left')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_Dssd_actual_s_or_w_approach_driver_right')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_dstopped_actual_n_or_e_approach_driver_left')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_dstopped_actual_n_or_e_approach_driver_right')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_dstopped_actual_s_or_w_approach_driver_left')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_dstopped_actual_s_or_w_approach_driver_right')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_stopping_sight_distance_actual_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_measure_stopping_sight_distance_actual_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_observe_sightline_obstructions')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_buildings_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_buildings_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_buildings_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_buildings_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_equipment_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_equipment_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_equipment_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_equipment_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_rail_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_rail_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_rail_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_rail_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_road_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_road_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_road_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_horizontal_and_Vertical_alignment_road_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_other_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_other_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_other_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_other_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_roadside_commercial_signing_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_roadside_commercial_signing_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_roadside_commercial_signing_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_roadside_commercial_signing_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_topography_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_topography_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_topography_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_topography_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_traffic_control_devices_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_traffic_control_devices_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_traffic_control_devices_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_traffic_control_devices_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Utility_and_lighting_poles_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Utility_and_lighting_poles_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Utility_and_lighting_poles_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Utility_and_lighting_poles_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_rail_row_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_rail_row_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_rail_row_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_rail_row_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_road_row_ne')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_road_row_nw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_road_row_se')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_restrictions_Vegetation_control_road_row_sw')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_road_stopping_sight_distance_n_or_e_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('sightlines_road_stopping_sight_distance_s_or_w_approach')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_advisory_speed_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_do_not_stop_on_track_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_emergency_notification_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_number_of_tracks_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_posted_speed_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_private_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_private_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_ahead_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_reflective_stripes_on_sign')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_approach_reflective_stripes_post_back')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_n_or_e_approach_reflective_stripes_post_front')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_reflective_stripes_of_sign')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_reflective_stripes_post_back')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_railway_crossing_s_or_w_approach_reflective_stripes_post_front')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_RR_crossing_symbols_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_sidewalks_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_sidewalks_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stop_sign_Ahead_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_stoplines_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_train_whistle_Prohibited_s_or_w_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_n_or_e_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_n_or_e_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_n_or_e_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_n_or_e_approach_present')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_s_or_w_approach_height')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_s_or_w_approach_location_from_rail')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_s_or_w_approach_location_from_road')
        )
        self.mapper.addMapping(
            self.view.temp,
            self.db.db_model_crossing_assessment_ca.fieldIndex('signs_and_pavement_markings_Two_train_event_s_or_w_approach_present')
        )  